bug: 동일 사용자가 같은 헬스장에 중복해서 등록 요청을 보내지 못하도록 수정 (#280)
NewFit/NewFit-Backend pull request #281
Opened 2023-12-01 09:41 UTC by hoyun06

## 개요
- close #280 
## 작업사항
- AuthorityService register 메소드 내부 중복 체크 로직
- test 추가

2023-12-01 15:58 UTC, Sangwook02 requested changes
확인 부탁드려요

2023-12-01 15:58 UTC, Sangwook02 commented on src/main/java/com/newfit/reservation/domains/authority/service/AuthorityService.java
> +        validateAuthorityDuplicate(userId, gymId);
위에서 user랑 gym을 조회하기 전에 먼저 validation을 하는게 효율적일 것 같습니다!

2023-12-01 15:58 UTC, Sangwook02 commented on src/main/java/com/newfit/reservation/domains/authority/service/AuthorityService.java
> +        Authority authority = authorityRepository.findOneByUserIdAndGymIdAndRoleType(userId, gymId, RoleType.USER);
[이 글](https://jojoldu.tistory.com/516) 참고해서 존재 여부를 확인하는 메서드를 구현해도 좋을 것 같습니다.

2023-12-01 15:58 UTC, Sangwook02 commented on src/main/java/com/newfit/reservation/domains/authority/service/AuthorityService.java
> +        Authority authority = authorityRepository.findOneByUserIdAndGymIdAndRoleType(userId, gymId, RoleType.USER);
별개로 findOneByUserIdAndGymIdAndRoleType 메서드 자체를 Optional을 반환하도록 바꾸면 어떨까요?
이 메서드 사용처가 하나 더 있던데 if문을 하나 줄일 수 있어서 좋을 것 같습니다.

2023-12-02 02:18 UTC, hoyun06 commented on src/main/java/com/newfit/reservation/domains/authority/service/AuthorityService.java
> +        validateAuthorityDuplicate(userId, gymId);
수정했습니다!

2023-12-02 02:18 UTC, hoyun06 commented on src/main/java/com/newfit/reservation/domains/authority/service/AuthorityService.java
> +        Authority authority = authorityRepository.findOneByUserIdAndGymIdAndRoleType(userId, gymId, RoleType.USER);
JpaRepository 내에도 자체적으로 existsBy~ 쿼리 메서드를 지원해서 우선은 그걸 사용했고
기존에 있던 findOneByUserIdAndGymIdAndRoleType 는 Optional 반환하도록 수정했습니다

2023-12-02 02:25 UTC, Sangwook02 approved these changes
Lgtm

2023-12-04 05:50 UTC, Lee-sh98 approved these changes
GOOD

2023-12-04 05:50 UTC, merged