refactor: 기구 예약 시간 validation 로직 수정 (#309)
NewFit/NewFit-Backend pull request #311
Opened 2023-12-27 16:10 UTC by hoyun06

## 개요
- close #309 

## 작업사항
- startAt 필드에 적용된 Future 어노테이션 제거
- validateStartAtLowerBound 메서드 추가
- reserve 및 update 메서드 내부 로직 수정

2023-12-28 16:18 UTC, Sangwook02 requested changes

2023-12-28 16:18 UTC, Sangwook02 commented on src/main/java/com/newfit/reservation/domains/reservation/service/ReservationService.java
> +	private void validateMyReservationOverlap(Authority authority, LocalDateTime startAt, LocalDateTime endAt,
메서드 명이 기존 메서드랑 겹쳐서 수정이 필요할 것 같습니다.

2023-12-31 06:16 UTC, Sangwook02 approved these changes

2024-01-02 03:43 UTC, Lee-sh98 approved these changes

2024-01-02 03:47 UTC, merged